In [ ]:
marks = [45, 60, 72, 38, 90]

total = 0

for i in range(len(marks) - 1):
    total += marks[i]

average = total / len(marks)

if average > 50:
    print("Class passed")
else:
    print("Class failed")
print(average)

Class failed
43.0

In [ ]:
def result(marks):
  avg=sum(marks)/len(marks)
  if avg>40:
    return "pass"
  else:
    return "fail"
marks = [45, 60, 72, 38, 90]
print(result(marks))

pass

In [ ]:
import numpy as np
import pandas as pd
arr=np.arange(8).reshape(2,2,2)
print(arr)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

In [ ]:
marks = np.array([78,91,55,72,40,88]).reshape(2,3)
print(marks.max())

91

• Find the average final_project_score.
• Find students with study_hours_per_week greater than 8.
• Compare average marks of Mumbai students and Pune students.
• Create a new column called performance_level.
• Save only selected columns to a new CSV.

In [ ]:
df=pd.read_csv("/content/session4_dummy_students_data.csv.xls")
df.describe()

,student_id,age,math,science,english,attendance_percent,study_hours_per_week,assignments_submitted,final_project_score
count,20.00000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000
mean,110.50000,16.450000,69.500000,72.350000,72.200000,83.850000,7.250000,7.750000,73.650000
std,5.91608,0.510418,18.446223,15.383775,17.157475,11.089469,3.092861,1.915999,17.439444
min,101.00000,16.000000,35.000000,45.000000,42.000000,62.000000,2.000000,4.000000,39.000000
25%,105.75000,16.000000,57.250000,60.000000,59.500000,76.500000,5.000000,6.000000,62.250000
50%,110.50000,16.000000,73.000000,74.500000,75.500000,87.500000,7.500000,8.000000,78.500000
75%,115.25000,17.000000,84.250000,85.250000,86.000000,92.500000,9.250000,9.250000,87.250000
max,120.00000,17.000000,95.000000,93.000000,96.000000,98.000000,13.000000,10.000000,96.000000

In [ ]:
df.head()

,student_id,name,age,city,math,science,english,attendance_percent,study_hours_per_week,assignments_submitted,final_project_score
0,101,Aarav,16,Mumbai,78,84,69,92,8,9,82
1,102,Diya,16,Delhi,91,88,94,96,11,10,93
2,103,Kabir,17,Mathura,55,61,58,75,5,6,60
3,104,Meera,16,Noida,72,79,81,89,7,8,78
4,105,Rohan,17,Mumbai,40,52,47,68,3,5,45

In [ ]:
df=pd.read_csv("/content/session4_dummy_students_data.csv.xls")
df.describe()
df["avg"] = df[["math", "science", "english"]].mean(axis=1)
df["result"] = "Fail"
df.loc[df["avg"] > 40, "result"] = "Pass"
print(df["avg"].mean())
print(df["avg"].min())
print(df["avg"].max())
print(df[df["avg"] == df["avg"].max()]["name"])
print(df[df["attendance_percent"]<75]["name"])
print(df[df["assignments_submitted"]<6]["name"])

71.35000000000001
40.666666666666664
92.66666666666667
15    Riya
Name: name, dtype: object
4      Rohan
8     Vivaan
12       Dev
18      Yash
Name: name, dtype: object
4     Rohan
12      Dev
18     Yash
Name: name, dtype: object

•	Find the average final_project_score.
•	Find students with study_hours_per_week greater than 8.
•	Compare average marks of Mumbai students and Pune students.
•	Create a new column called performance_level.
•	Save only selected columns to a new CSV.